language: c
sudo: required
env:
  global:
    - CHROOT_DIR=/tmp/arm-chroot
  matrix:
    - CHROOT_ARCH=x64
    - CHROOT_ARCH=armhf

#cache:
#  directories:
#    - $CHROOT_DIR

script:
  - bash -ex scripts/qemu-setup.sh
  - bash -ex scripts/qemu-test.sh
