language: c
sudo: required
env:
  global:
    - CHROOT_DIR=/tmp/arm-chroot
  matrix:
    - ARCH=x64
    - ARCH=arm

cache:
  directories:
    - $CHROOT_DIR

script:
  - "bash -ex scripts/qemu-setup.sh"
  - "bash -ex scripts/qemu-test.sh"
